brew:
- vim
- git
- tmux
- docker
- boot2docker
cask:
- virtualbox
- github
- gitifier
- macvim
- google-chrome
- fish
- fishapp
- firefox
- dropbox
- iterm2
- 1password
- atom
- kitematic
- docker-compose
- docker-machine
- transmission
- vlc
